services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fintech-assets-explorer
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./database:/var/www/html/database
            - ./storage:/var/www/html/storage
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        networks:
            - fintech-network

    # Optional: Add nginx as reverse proxy for production
    nginx:
        image: nginx:alpine
        container_name: fintech-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - fintech-network
        profiles:
            - production

networks:
    fintech-network:
        driver: bridge

volumes:
    database_data:
        driver: local
